workflows:
  android-guaranteed:
    name: Guaranteed Android Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Recreate Gradle Wrapper
        script: |
          cd android
          
          # Eski dosyaları temizle
          rm -rf gradle gradlew gradlew.bat
          echo "Cleaned old gradle files"
          
          # Yeni gradle wrapper oluştur
          gradle wrapper --gradle-version 8.4 --distribution-type all
          echo "Created new gradle wrapper"
          
          # Permission ayarla
          chmod +x gradlew
          echo "Gradlew permissions:"
          ls -la gradlew
          
          # Test et
          ./gradlew --version
          echo "Gradle version check completed"
          
      - name: Build APK
        script: |
          cd android
          ./gradlew clean assembleDebug --stacktrace --info
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
