workflows:
  android-simple:
    name: Simple Android Build
    scripts:
      - name: Setup and Build
        script: |
          npm install
          cd android
          
          # Gradle wrapper'ı tamamen yeniden oluştur
          rm -rf gradle gradlew gradlew.bat
          
          # Yeni gradle wrapper oluştur
          gradle wrapper --gradle-version 8.4
          
          # Build al
          ./gradlew clean assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
