workflows:
  android-simple:
    name: Simple Android Build
    scripts:
      - name: Setup and Build
        script: |
          npm install
          cd android
          ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
